spring:
  application:
    name: ticket-management-backend

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: Jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
